import fs from "node:fs/promises";
import path from "node:path";
import type { AssistantSpecialty, KnowledgeCitation } from "./types";
import { listVaultRecords, type VaultRecord } from "./store";
type KnowledgeRecord={id:string;title:string;source:string;text:string;tags?:string[];specialty?:AssistantSpecialty|"all";updatedAt?:string;status?:string};
const DIR=process.env.TREY_KNOWLEDGE_DIR?path.resolve(process.env.TREY_KNOWLEDGE_DIR):path.join(process.cwd(),"knowledge","private");
function tokens(value:string){return value.toLowerCase().replace(/[^a-z0-9'\s-]/g," ").split(/\s+/).filter(t=>t.length>2);}
async function walk(directory:string):Promise<string[]>{try{const entries=await fs.readdir(directory,{withFileTypes:true});return(await Promise.all(entries.map(async e=>{const target=path.join(directory,e.name);if(e.isDirectory())return walk(target);return e.isFile()&&e.name.endsWith(".json")&&!e.name.endsWith("vault.records.json")?[target]:[];}))).flat();}catch{return[];}}
async function legacyLoad():Promise<KnowledgeRecord[]>{const records:KnowledgeRecord[]=[];for(const file of await walk(DIR)){try{const value=JSON.parse(await fs.readFile(file,"utf8")) as KnowledgeRecord|KnowledgeRecord[];records.push(...(Array.isArray(value)?value:[value]));}catch{}}return records.filter(r=>r.id&&r.title&&r.source&&r.text);}
function scoreRecord(record:KnowledgeRecord|VaultRecord,queryTokens:Set<string>){const body=`${record.title} ${(record.tags||[]).join(" ")} ${record.text}`;return tokens(body).reduce((s,t)=>s+(queryTokens.has(t)?1:0),0)+tokens(record.title).reduce((s,t)=>s+(queryTokens.has(t)?3:0),0)+(record.status==="final"?2:0);}
export async function retrieveKnowledge(query:string,specialty:AssistantSpecialty,limit=10):Promise<{context:string;citations:KnowledgeCitation[]}>{const queryTokens=new Set(tokens(query));const vault=(await listVaultRecords()).filter(r=>["knowledge","memory","decision"].includes(r.kind)&&r.status!=="superseded");const combined:(KnowledgeRecord|VaultRecord)[]=[...vault,...await legacyLoad()];const ranked=combined.filter(r=>!r.specialty||r.specialty==="all"||r.specialty===specialty).map(record=>({record,score:scoreRecord(record,queryTokens)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit);const citations=ranked.map(({record},i)=>({id:`K${i+1}`,title:record.title,source:record.source,excerpt:record.text.slice(0,420),updatedAt:record.updatedAt}));const context=ranked.map(({record},i)=>`[K${i+1}] ${record.title}\nSource: ${record.source}\nUpdated: ${record.updatedAt||"unknown"}\nStatus: ${record.status||"active"}\n${record.text}`).join("\n\n");return{context,citations};}
export function getKnowledgeDirectory(){return DIR;}