"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
type RecordItem={id:string;kind:string;title:string;text:string;source:string;specialty?:string;status?:string;updatedAt:string};
export default function VaultPage(){
 const [records,setRecords]=useState<RecordItem[]>([]);const [busy,setBusy]=useState(false);const [form,setForm]=useState({kind:"knowledge",title:"",text:"",source:"Trey direct input",specialty:"all",tags:"",status:"active"});const [repoPath,setRepoPath]=useState("");const [message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/vault");const d=await r.json();setRecords(d.records||[]);}useEffect(()=>{void load();},[]);
 async function save(){setBusy(true);setMessage("");try{const r=await fetch("/api/vault",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,tags:form.tags.split(",").map(x=>x.trim()).filter(Boolean)})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Save failed");setForm({...form,title:"",text:"",tags:""});setMessage("Saved to Trey AI memory.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Save failed");}finally{setBusy(false)}}
 async function indexRepo(){setBusy(true);setMessage("Indexing repository...");try{const r=await fetch("/api/vault/index-repo",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({repoPath})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Index failed");setMessage(`Indexed ${d.fileCount} files.`);await load();}catch(e){setMessage(e instanceof Error?e.message:"Index failed");}finally{setBusy(false)}}
 return <main className="trey-shell"><header className="trey-header"><div><span className="eyebrow">PRIVATE KNOWLEDGE</span><h1>Trey AI Vault</h1><p>Confirmed memories, catalog facts, decisions and repository intelligence.</p></div><div className="header-actions"><Link className="studio-link" href="/">Back to Trey AI</Link></div></header><section className="vault-grid"><div className="vault-card"><h2>Add knowledge or memory</h2><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="knowledge">Knowledge</option><option value="memory">Memory</option><option value="decision">Decision</option></select><input placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea rows={8} placeholder="What should Trey AI know?" value={form.text} onChange={e=>setForm({...form,text:e.target.value})}/><input placeholder="Source" value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/><input placeholder="Tags, separated by commas" value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/><div className="vault-row"><select value={form.specialty} onChange={e=>setForm({...form,specialty:e.target.value})}><option value="all">All specialties</option><option value="songwriting">Songwriting</option><option value="inside-ar">Inside A&R</option><option value="catalog">Catalog</option><option value="coding">Coding</option><option value="general">General</option></select><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="final">Final</option><option value="draft">Draft</option></select></div><button onClick={()=>void save()} disabled={busy||!form.title||!form.text}>Save to Vault</button></div><div className="vault-card"><h2>Index a repository</h2><p>Use a folder path accessible from the server running Trey AI.</p><input placeholder="/teamspace/studios/this_studio/trizzy-writer" value={repoPath} onChange={e=>setRepoPath(e.target.value)}/><button onClick={()=>void indexRepo()} disabled={busy||!repoPath}>Index Repository</button><p className="vault-message">{message}</p></div></section><section className="vault-card vault-list"><h2>Stored intelligence · {records.length}</h2>{records.map(r=><article key={r.id}><div><strong>{r.title}</strong><span>{r.kind} · {r.specialty||"all"} · {r.status||"active"}</span></div><p>{r.text.slice(0,280)}{r.text.length>280?"…":""}</p><small>{r.source} · {new Date(r.updatedAt).toLocaleString()}</small></article>)}</section></main>;
}