import { NextResponse } from "next/server";
import { z } from "zod";
import fs from "node:fs/promises";
import path from "node:path";
import { saveVaultRecord } from "@/lib/assistant/store";
export const runtime="nodejs"; export const dynamic="force-dynamic"; export const maxDuration=180;
const schema=z.object({repoPath:z.string().min(1),name:z.string().min(1).max(200).optional()});
const allowedExt=new Set([".ts",".tsx",".js",".jsx",".json",".md",".sql",".py",".sh",".yml",".yaml",".toml"]);
const ignored=new Set(["node_modules",".git",".next","dist","build","coverage",".turbo",".vercel"]);
async function walk(dir:string,root:string,depth=0):Promise<string[]>{if(depth>8)return[];const out:string[]=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){if(ignored.has(e.name))continue;const full=path.join(dir,e.name);if(e.isDirectory())out.push(...await walk(full,root,depth+1));else if(allowedExt.has(path.extname(e.name).toLowerCase()))out.push(path.relative(root,full));if(out.length>=2500)break;}return out;}
export async function POST(request:Request){const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Invalid repository request."},{status:400});const root=path.resolve(parsed.data.repoPath);try{const stat=await fs.stat(root);if(!stat.isDirectory())throw new Error("Not a directory");}catch{return NextResponse.json({error:"Repository path is unavailable to this server."},{status:400});}const files=await walk(root,root);let pkg:Record<string,unknown>={};try{pkg=JSON.parse(await fs.readFile(path.join(root,"package.json"),"utf8"));}catch{}const sample:string[]=[];for(const rel of files.slice(0,120)){try{const txt=await fs.readFile(path.join(root,rel),"utf8");sample.push(`FILE ${rel}\n${txt.slice(0,2500)}`);}catch{}}const title=parsed.data.name||path.basename(root);const text=`Repository: ${title}\nPath: ${root}\nIndexed files: ${files.length}\nScripts: ${JSON.stringify(pkg.scripts||{})}\nDependencies: ${JSON.stringify(pkg.dependencies||{})}\n\nFILE MAP\n${files.join("\n")}\n\nCODE SAMPLE\n${sample.join("\n\n")}`;const record=await saveVaultRecord({kind:"knowledge",title:`Repository · ${title}`,text,source:`Local repository index: ${root}`,specialty:"coding",tags:["repository",title,"codebase"],status:"active",confidence:"confirmed",sensitivity:"confidential",metadata:{repoPath:root,fileCount:files.length}});return NextResponse.json({record,fileCount:files.length});}