"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import type { AssistantChatMessage, AssistantResponse, AssistantSpecialty } from "@/lib/assistant/types";

type UiMessage = AssistantChatMessage & { specialty?: AssistantSpecialty; citations?: AssistantResponse["citations"] };
const STORAGE_KEY = "trey-ai-chat-v1";
const labels: Record<AssistantSpecialty,string> = { songwriting:"Songwriter", "inside-ar":"Inside A&R", catalog:"Catalog", coding:"Code", general:"Assistant" };
export default function Home() {
  const [messages,setMessages]=useState<UiMessage[]>([]); const [input,setInput]=useState(""); const [loading,setLoading]=useState(false); const [status,setStatus]=useState("Ready"); const endRef=useRef<HTMLDivElement|null>(null);
  useEffect(()=>{ try { const saved=localStorage.getItem(STORAGE_KEY); if(saved) setMessages(JSON.parse(saved)); } catch {} },[]);
  useEffect(()=>{ localStorage.setItem(STORAGE_KEY,JSON.stringify(messages.slice(-80))); endRef.current?.scrollIntoView({behavior:"smooth"}); },[messages]);
  async function send(){ const text=input.trim(); if(!text||loading)return; const next=[...messages,{role:"user",content:text} as UiMessage]; setMessages(next); setInput(""); setLoading(true); setStatus("Trey AI is thinking..."); try { const response=await fetch("/api/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,history:next.map(({role,content})=>({role,content}))})}); const data=await response.json() as AssistantResponse|{error:string}; if(!response.ok||!("text" in data)) throw new Error("error" in data?data.error:"Request failed."); setMessages(current=>[...current,{role:"assistant",content:data.text,specialty:data.specialty,citations:data.citations}]); setStatus(`${labels[data.specialty]} active`); } catch(error){ setMessages(current=>[...current,{role:"assistant",content:error instanceof Error?error.message:"Trey AI could not respond."}]); setStatus("Connection issue"); } finally { setLoading(false); } }
  return <main className="trey-shell"><header className="trey-header"><div><span className="eyebrow">PRIVATE INTELLIGENCE</span><h1>Trey AI</h1><p>One assistant for music, A&R, catalog, code and everything you are building.</p></div><div className="header-actions"><span className="status-dot">{status}</span><Link href="/studio" className="studio-link">Open Writer Studio</Link></div></header><section className="chat-panel"><div className="chat-scroll">{messages.length===0?<div className="welcome"><div className="orb">T</div><h2>What are we working on?</h2><p>Ask naturally. Trey AI will bring in the right specialty behind the scenes.</p><div className="prompt-grid">{["Write me a full song about finally being chosen.","What should my next release priority be?","Which of my songs has a similar theme to this idea?","Scan my app architecture and help me plan the next feature."].map(item=><button key={item} onClick={()=>setInput(item)}>{item}</button>)}</div></div>:messages.map((message,index)=><article key={index} className={`bubble ${message.role}`}><div className="bubble-meta">{message.role==="user"?"You":labels[message.specialty||"general"]}</div><div className="bubble-text">{message.content}</div>{message.citations?.length?<details><summary>{message.citations.length} knowledge sources</summary>{message.citations.map(c=><div className="citation" key={c.id}><strong>{c.id} · {c.title}</strong><span>{c.source}</span><p>{c.excerpt}</p></div>)}</details>:null}</article>)}{loading?<article className="bubble assistant"><div className="typing"><span></span><span></span><span></span></div></article>:null}<div ref={endRef}/></div><div className="composer"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send();}}} placeholder="Message Trey AI..." rows={3}/><div className="composer-row"><span>Enter to send · Shift+Enter for a new line</span><button onClick={()=>void send()} disabled={loading||!input.trim()}>{loading?"Working...":"Send"}</button></div></div></section></main>;
}
