"use client";
import Link from "next/link";
import { useEffect,useRef,useState } from "react";
import type { AssistantChatMessage,AssistantResponse,AssistantSpecialty } from "@/lib/assistant/types";
type UiMessage=AssistantChatMessage&{specialty?:AssistantSpecialty;citations?:AssistantResponse["citations"];saved?:boolean};
const STORAGE_KEY="trey-ai-chat-v2";const SESSION_KEY="trey-ai-session";const labels:Record<AssistantSpecialty,string>={songwriting:"Songwriter","inside-ar":"Inside A&R",catalog:"Catalog",coding:"Code",general:"Assistant"};
export default function Home(){const[messages,setMessages]=useState<UiMessage[]>([]);const[input,setInput]=useState("");const[loading,setLoading]=useState(false);const[status,setStatus]=useState("Ready");const[sessionId,setSessionId]=useState("");const endRef=useRef<HTMLDivElement|null>(null);
useEffect(()=>{try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)setMessages(JSON.parse(saved));let sid=localStorage.getItem(SESSION_KEY);if(!sid){sid=crypto.randomUUID();localStorage.setItem(SESSION_KEY,sid);}setSessionId(sid);}catch{}},[]);useEffect(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(messages.slice(-80)));endRef.current?.scrollIntoView({behavior:"smooth"});},[messages]);
async function send(){const text=input.trim();if(!text||loading)return;const next=[...messages,{role:"user",content:text} as UiMessage];setMessages(next);setInput("");setLoading(true);setStatus("Trey AI is thinking...");try{const response=await fetch("/api/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,history:next.map(({role,content})=>({role,content})),sessionId})});const data=await response.json() as AssistantResponse|{error:string};if(!response.ok||!("text" in data))throw new Error("error" in data?data.error:"Request failed.");setMessages(current=>[...current,{role:"assistant",content:data.text,specialty:data.specialty,citations:data.citations}]);setStatus(`${labels[data.specialty]} active`);}catch(error){setMessages(current=>[...current,{role:"assistant",content:error instanceof Error?error.message:"Trey AI could not respond."}]);setStatus("Connection issue");}finally{setLoading(false);}}
async function remember(message:UiMessage,index:number,statusValue:"active"|"final"){const previous=messages.slice(0,index).reverse().find(m=>m.role==="user");const response=await fetch("/api/vault",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:statusValue==="final"?"decision":"memory",title:statusValue==="final"?"Approved final Trey AI result":"Remembered Trey AI result",text:`Request: ${previous?.content||"Unknown"}\n\nResult: ${message.content}`,source:"Trey approval in unified chat",specialty:message.specialty||"general",tags:["approved","chat"],status:statusValue,confidence:"confirmed",sensitivity:"private"})});if(response.ok)setMessages(current=>current.map((m,i)=>i===index?{...m,saved:true}:m));setStatus(response.ok?"Saved to permanent memory":"Memory save failed");}
return <main className="trey-shell"><header className="trey-header"><div><span className="eyebrow">PRIVATE INTELLIGENCE</span><h1>Trey AI</h1><p>One assistant for music, A&R, catalog, code and everything you are building.</p></div><div className="header-actions"><span className="status-dot">{status}</span><Link href="/vault" className="studio-link">Knowledge Vault</Link><Link href="/studio" className="studio-link">Writer Studio</Link></div></header><section className="chat-panel"><div className="chat-scroll">{messages.length===0?<div className="welcome"><div className="orb">T</div><h2>What are we working on?</h2><p>Ask naturally. Trey AI will bring in the right specialty and your private knowledge behind the scenes.</p><div className="prompt-grid">{["Write me a full song about finally being chosen.","What should my next release priority be?","Which of my songs has a similar theme to this idea?","Scan my app architecture and help me plan the next feature."].map(item=><button key={item} onClick={()=>setInput(item)}>{item}</button>)}</div></div>:messages.map((message,index)=><article key={index} className={`bubble ${message.role}`}><div className="bubble-meta">{message.role==="user"?"You":labels[message.specialty||"general"]}</div><div className="bubble-text">{message.content}</div>{message.role==="assistant"?<div className="memory-actions"><button disabled={message.saved} onClick={()=>void remember(message,index,"active")}>{message.saved?"Saved":"Remember"}</button><button disabled={message.saved} onClick={()=>void remember(message,index,"final")}>Save as Final</button></div>:null}{message.citations?.length?<details><summary>{message.citations.length} knowledge sources</summary>{message.citations.map(c=><div className="citation" key={c.id}><strong>{c.id} · {c.title}</strong><span>{c.source}</span><p>{c.excerpt}</p></div>)}</details>:null}</article>)}{loading?<article className="bubble assistant"><div className="typing"><span></span><span></span><span></span></div></article>:null}<div ref={endRef}/></div><div className="composer"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send();}}} placeholder="Message Trey AI..." rows={3}/><div className="composer-row"><span>Enter to send · Shift+Enter for a new line</span><button onClick={()=>void send()} disabled={loading||!input.trim()}>{loading?"Working...":"Send"}</button></div></div></section></main>;
}